### ISSUE TITLE
Display the sway build DAG

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway-vscode-plugin#105]
Add a command palette for showing the workspace build DAG. The graph is generated [here](https://github.com/FuelLabs/sway/blob/88b4cc572d8412dd3272d07c7e62bf14f7555b55/forc-pkg/src/pkg.rs#L2404). We should display the dotfile contents cleanly in a VSCode sidebar. Just the name of the contract in each bubble will be fine for now.

**Comment by JoshuaBatty** [comment]
Might be something worth looking into [here](https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview)
