### ISSUE TITLE
Lots of warnings with latest toolchain

### ISSUE THREAD

**Issue by PaulRBerg** [FuelLabs/sway-vscode-plugin#161]
## Problem

Compiling a Sway contract with the latest syntax/ toolchain results in many warnings produced by the Sway VSCode extension:

- "This storage declaration is never accessed and can be removed"
- "This declaration is never used"

## Screenshot

<img width="350" alt="Screenshot 2023-09-26 at 2 08 32 PM" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/8782666/317744e7-62a3-4366-8125-9c3b2a31dbbc">

## Environment

- macOS 13.5.2
- VSCode 1.82.2
- forc 0.46.0
- fuel-core 0.20.5

**Comment by JoshuaBatty** [comment]
Thanks for the issue @PaulRBerg we'll look into it asap.

**Comment by sdankel** [comment]
@PaulRBerg This should be fixed, if it's still happening with the latest version of `forc-lsp`, please reopen this issue.
