### ISSUE TITLE
Syntax highlighting is inconsistent

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway-vscode-plugin#22]
The act of adding or deleting a new line sometimes affects highlighting further down.

I've uploaded a screen recording to demonstrate this.
https://user-images.githubusercontent.com/17053076/150178127-23d36f93-69de-4636-b201-d8f13d805e6e.mov

Also, some comments starting with `///` act weird. deleting 1 `/` symbol and then adding it back resolves this.

**Comment by adlerjohn** [comment]
So long as saving the file produces the correct highlighting at the end, I don't think transient bad highlighting is a big deal. Can I close for now?

**Comment by nfurfaro** [comment]
Closing for now as I can't repro.
If this resurfaces I'll re-open with more detail.

**Comment by JoshuaBatty** [comment]
Going to reopen this issue as I think it might be related to [this](https://github.com/FuelLabs/sway/issues/1177) and [this](https://github.com/FuelLabs/sway/issues/1147) issue in 'sway-lsp'

**Comment by JoshuaBatty** [comment]
This has been resolved in https://github.com/FuelLabs/sway/pull/2919
