### ISSUE TITLE
Implementing an ABI should automatically fill in the ABI methods

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway-vscode-plugin#38]
Typing `impl <ABI name>` in a `contract` file should automatically fill in the rest of the line (`for Contract`) and generate skeleton method definitions.

**Comment by JoshuaBatty** [comment]
This functionality was added as a code_action here https://github.com/FuelLabs/sway/pull/3464

Closing as it makes more sense to be a code action rather than an autocomplete feature.
