### ISSUE TITLE
sway vscode plugin crashes on start up

### ISSUE THREAD

**Issue by binggh** [FuelLabs/sway-vscode-plugin#42]
The sway vscode plugin immediately crashes on startup.

This is probably due to the changes to the LSP feature becoming a plugin instead of a native command: https://github.com/FuelLabs/sway/pull/1178

```
Error: no such subcommand: `lsp`
[Info  - 4:21:53 PM] Connection to server got closed. Server will restart.
Error: no such subcommand: `lsp`
[Info  - 4:21:53 PM] Connection to server got closed. Server will restart.
Error: no such subcommand: `lsp`
[Info  - 4:21:53 PM] Connection to server got closed. Server will restart.
Error: no such subcommand: `lsp`
[Info  - 4:21:53 PM] Connection to server got closed. Server will restart.
Error: no such subcommand: `lsp`
[Error - 4:21:53 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by mitchmindtree** [comment]
@binggh you might just need to install the `forc-lsp` plugin - could you try `cargo install forc-lsp`, then re-launch VS Code and see if that works?

I haven't looked into how VS Code plugins work yet myself (I do my editing with Vim), but perhaps there's some way we can make sure `forc-lsp` is installed during the plugin installation process.

**Comment by adlerjohn** [comment]
I think this should mostly be resolved once we have binary distributions. In the meantime, if that is indeed the fix, then The Book can simply be update to include instruction to install the lsp and other important plugins.

**Comment by binggh** [comment]
@mitchmindtree oops, my bad - that fixed it 😅  will close this issue and update the docs at https://fuellabs.github.io/sway/latest/introduction/sway-toolchain.html
