### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway-vscode-plugin#43]
We should use the Sway logo here:
https://marketplace.visualstudio.com/items?itemName=FuelLabs.sway-vscode-plugin

**Comment by adlerjohn** [comment]
@SilentCicero please update the PR description with the Sway logo.

**Comment by sdankel** [comment]
Asking the design team about the logo ([slack](https://fuellabs.slack.com/archives/C01JWU4DLKH/p1655100191013089))

**Comment by eureka-cpu** [comment]
🎉
