### ISSUE TITLE
'storage' keyword should be highlighted in vs-code

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway-vscode-plugin#46]
Technically speaking, I'm not certain that "storage" is actually a keyword, but it should be highlighted regardless.

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/sway-vscode-plugin/blob/5f7e27c41d5ec6fe5f750bb079dad44fd59cab68/syntaxes/sway.tmLanguage.json#L254

**Comment by nfurfaro** [comment]
I'm not sure if this is something that should already be working, or needs to be done?
I'm using the latest version (`v0.2.2`) and it doesn't work yet.
cc @mitchmindtree
