### ISSUE TITLE
Add a "run" button on top of `main` function 

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway-vscode-plugin#54]
Rust analyzer has a run & debug button that hovers above the main function. It would be cool to provide a run button and add a debug option when debugging becomes available. 

There will have to be some communication with the language server for this to the VS Code plugin, i.e the server needs to determine if the file is a script, if a `main` function is present, and where in the code the `main` function is located. Using this information the type script code then knows if it should, and where to place the run button in the editor. 

![VS Code run](https://user-images.githubusercontent.com/1289413/172736450-7fbc419e-e97f-44fe-b6ee-d489a9bbde05.jpg)

**Comment by sdankel** [comment]
Love this idea! Let me know if you want to collaborate on the language server interface. It looks like we could do something really similar to [this](https://github.com/rust-lang/rust-analyzer/blob/c567771605631c786af8b3d21204abad857e04ac/editors/code/src/lsp_ext.ts#L109-L124) using vscode language client generic types.

I'd be happy to work on the vscode plugin UX when the backend is ready 😄
