### ISSUE TITLE
Custom types should be highlighted similar to primitive types e.g. `u64`.

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-vscode-plugin#59]
# Summary

Taking a look at the imports (_use..._) and the custom types declared as parameter types it can be seen that they are white / not highlighted while the `u64` is highlighted.

Add highlights so that the custom types are highlighted in the function (parameter types) and imports.
Perhaps data structures such as `struct` & `enum` should be one colour while imported functions should be another colour.

# Screenshot

![1](https://user-images.githubusercontent.com/103777923/173524099-cf071418-c4b2-406f-b509-d119765ed922.png)

**Comment by sdankel** [comment]
Fixed in https://github.com/FuelLabs/sway-vscode-plugin/pull/80
