### ISSUE TITLE
Function parameters should be easily distinguishable from those declared inside the function

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-vscode-plugin#60]
# Summary

It can be seen in the screenshot that the variables defined as parameters are italicised however that does not continue to be the case in the function body.

Perhaps the parameters should also be coloured and have the same formatting in the function body to make it easier to distinguish between

1. storage usage (once a new release is out that might add colour, #50)
2. variables defined in the function body
3. variables passed into the function

# Screenshot

![1](https://user-images.githubusercontent.com/103777923/173525518-9e438b9a-a0ac-4e87-8e76-b08c78efc860.png)

**Comment by sdankel** [comment]
Fixed in https://github.com/FuelLabs/sway-vscode-plugin/pull/80
