### ISSUE TITLE
New `storage` keyword highlighting applies highlighting when importing modules

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-vscode-plugin#63]
# Summary

Personally, I'm not a fan of the colour at all but I can try to ignore that - pls change it to be light grey or green or something.
What I cannot ignore is that `storage` is highlighted in more places than it should be highlighted e.g. when you declare storage for a contract to use.
Specifically, `storage` being individually highlighted when you import modules from `std`.
The highlighting applies as you'd expect it when using it in functions.

# Screenshot
![1](https://user-images.githubusercontent.com/103777923/174279466-82f5faf3-d2d8-43f0-b49b-0c5dc3a5b5cb.png)

**Comment by JoshuaBatty** [comment]
also adding Syd's other screen shot from Slack for future reference. 

![1](https://user-images.githubusercontent.com/1289413/174286283-60e4a817-b45d-416b-bc9f-a196088d2b88.png)

**Comment by adlerjohn** [comment]
This is because `storage` is a keyword, so it's naively highlighted. This brings up a good question, of whether or not it should be forbidden for a library to be called `storage`.

**Comment by adlerjohn** [comment]
Related: https://github.com/FuelLabs/sway/issues/1996

**Comment by sdankel** [comment]
Fixed in https://github.com/FuelLabs/sway-vscode-plugin/pull/80

<img width="430" alt="image" src="https://user-images.githubusercontent.com/47993817/186186597-e8809526-431f-40d2-a5fb-6f5a8df803a1.png">
