### ISSUE TITLE
Highlight attribute bodies differently

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway-vscode-plugin#64]
also adding @Braqzen's other screen shot from Slack for future reference. Ideally, the `storage` keyword on attributes should be a lighter colour. 

![1](https://user-images.githubusercontent.com/1289413/174286283-60e4a817-b45d-416b-bc9f-a196088d2b88.png)

_Originally posted by @JoshuaBatty in https://github.com/FuelLabs/sway-vscode-plugin/issues/63#issuecomment-1158760612_

**Comment by JoshuaBatty** [comment]
Some more examples of highlighting bugs from Slack. 

the `campaign_info` fn isn't highlighting `storage`, yet it's getting highlighted elsewhere. 
![1 (2)](https://user-images.githubusercontent.com/1289413/174918386-2e31b396-47a3-4198-a1dc-1d8a3ad04b1f.png)

Notice that the top `storage` is not highlighted.
![1 (1)](https://user-images.githubusercontent.com/1289413/174918409-d9dfe11a-fe4d-4add-87ed-887dbfb4f351.png)
