### ISSUE TITLE
`forc-lsp` is not detected when installed via `fuelup` and the error message needs improvement

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-vscode-plugin#67]
# Summary

When I start VSCode the first thing that I see is a pop up in the bottom right stating that the LSP has crashed multiple times.
Moreover, checking the "OUTPUT" section I see a bunch of errors indicating that `forc` has not been found and eventually the server stops attempting to connect.

Checking my toolchain I find that I do have `forc` and `forc-lsp` installed under `~/.fuelup/some/path/` however since I use `fuelup` I no longer have a need for the old `~/.forc` directory (which `fuelup` recommends to remove iirc) and thus my suspicion is that the plugin is looking in the old directory and fails to find whatever it is looking for since it no longer exists.

The error message should be improved and if the the plugin is not looking in the correct place then `fuelup` should be added for support.

# Screenshots

![1](https://user-images.githubusercontent.com/103777923/175781588-a293bc52-3dde-43b1-9c1f-42d0ad5e46c5.png)
![2](https://user-images.githubusercontent.com/103777923/175781589-f87735c0-151c-41cd-9c7c-83c10cbef286.png)

**Comment by adlerjohn** [comment]
Can you confirm that `forc-lsp` and `forc` are in your `PATH` by running `which forc-lsp` and `which forc`? If they produce no output, or different directories, then that's indicative that your `PATH` was set incorrectly.

**Comment by Braqzen** [comment]
> Can you confirm that `forc-lsp` and `forc` are in your `PATH` by running `which forc-lsp` and `which forc`? If they produce no output, or different directories, then that's indicative that your `PATH` was set incorrectly (either by `fuelup`, or manually).

![1](https://user-images.githubusercontent.com/103777923/175786627-739f8063-ae02-4cad-9257-d539ddf59f59.png)

**Comment by adlerjohn** [comment]
One more thought @Braqzen: Could you `echo $PATH`? There's an issue with using `~` in PATH that made me encounter the same bug and wondering it that might be it.

**Comment by Braqzen** [comment]
> 

![1](https://user-images.githubusercontent.com/103777923/175786896-a69a36b7-b72a-4ca8-81a5-1e8462c28bb0.png)

**Comment by sdankel** [comment]
@Braqzen does this still repro for you? I believe this should be fixed.
