### ISSUE TITLE
`struct` and `enum` keywords are not the correct highlight color

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway-vscode-plugin#72]
the `struct` and `enum` keywords are being incorrectly highlighted. Also, enum variants are highlighted differently depending on if they contain data or not.

I'm using the `match_expressions_mismatched` example in the sway repo e2e tests folder as an example here. Below you can see how the tokens are highlighted currently in sway. 
 
<img width="467" alt="sway-lsp example" src="https://user-images.githubusercontent.com/1289413/177486750-94748bef-cb8d-4c24-a99e-88e5950a3459.png">

And copying that same example into a new rust project, you can see the correct color highlighting that we should be doing. 

<img width="467" alt="rust-analyzer example" src="https://user-images.githubusercontent.com/1289413/177486862-d4cce1d5-b08d-475e-8fe4-27513ea79896.png">

related to #59

**Comment by sdankel** [comment]
@JoshuaBatty Which VSCode theme are you using? Do you have `tokenColorCustomizations` set in your settings.json?

I'm using Default Dark+ and see this:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/47993817/181864732-bd87f508-6713-4296-947b-2a0715bd3cb5.png">

The `struct` and `enum` keywords look correct, although I see other problems: 
- enum variants are highlighted differently
- enum and struct names are not highlighted
- variable names are not highlighted

**Comment by sdankel** [comment]
I found some documentation about text mate grammars (tmLanguage files) [here](https://macromates.com/manual/en/language_grammars)

I was able to get it pretty close to the rust syntaxes highlighting by copying the [rust tmLanguage.json](https://raw.githubusercontent.com/dustypomerleau/rust-syntax/master/syntaxes/rust.tmLanguage.json) and swapping in 'sway' for 'rust'. There's still a slight difference (enum members aren't highlighted the same color) but it looks a lot closer.

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/47993817/181865451-85af40b9-b5b5-4548-8c86-8b3b5e145c97.png">

**Comment by sdankel** [comment]
A longer example: `abort_control_flow_good/src/main.sw` 
It looks very close indeed.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/47993817/181865723-5f2dce74-1f3f-4881-bb77-562072b873f1.png">
