### ISSUE TITLE
Make `stopFuelCore` command palette portable to Windows

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway-vscode-plugin#90]
Related: https://github.com/FuelLabs/sway-vscode-plugin/pull/89#discussion_r952015031

**Comment by JoshuaBatty** [comment]
Not sure if this should be an open issue worth tracking considering we only officially support unix systems with `fuelup` and `fuel.nix`. Windows users should be encouraged to use WSL in which case the `stopFuelCore` command should already be working. 

Are you happy if we close this issue @sdankel ?
