### ISSUE TITLE
VSCode Editor and Marketplace changelogs are empty

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/sway-vscode-plugin#94]
I noticed that changelogs have not been updated.

Here is the one shown within VSCode:
![image](https://user-images.githubusercontent.com/833485/191625586-e683cbaa-7621-47cb-bfd1-5f3bae934683.png)

Also on the [VS marketplace](https://marketplace.visualstudio.com/items/FuelLabs.sway-vscode-plugin/changelog):
![image](https://user-images.githubusercontent.com/833485/191625520-9dacc6bd-0823-4fbd-a03f-62203d1cb110.png)

It would be nice to show something here I think.

**Comment by adlerjohn** [comment]
We don't really have anything set up in CI to handle a changelog file properly. Would a better approach be to remove the changelog entirely and just point people to release notes?

**Comment by JoshuaBatty** [comment]
this is implemented now. closing.
